######################## default configuration ####################
baseURL = "https://portfolio.susannahfisher.art/"
languageCode = "en-us"
title = "Susannah Fisher"
theme = "pou"
summaryLength = "10"
paginate = 6
disqusShortname = ""

[outputs]
home = ["HTML", "RSS", "JSON"]

[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5

############################# Plugins ##############################
[params.plugins]

# CSS Plugins
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
URL = "plugins/venobox/venobox.css"

# JS Plugins
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
URL = "plugins/search/fuse.min.js"
[[params.plugins.js]]
URL = "plugins/search/mark.js"
[[params.plugins.js]]
URL = "plugins/search/search.js"


############################## navigation ###############################
[menu]

# main menu
# Work

[[menu.main]]
name = "Natural History Illustration"
URL = "work/naturalhistoryillustration/"
weight = 1

[[menu.main]]
name = "Portraits"
URL = "work/portraits/"
weight = 2

[[menu.main]]
name = "Visual Journalism"
URL = "work/visual-journalism/"
weight = 3

[[menu.main]]
identifier = 'substack'
name = "Writing"
url = ''
weight = 4

# [[menu.main]]
# name = "Beautiful Ordinary Life"
# parent = 'substack'
# URL = "https://beautifulordinarylife.substack.com"
# weight = 1

[[menu.main]]
name = "A Naturalist's Notebook"
parent = 'substack'
URL = "https://anaturalistsnotebook.substack.com"
weight = 2


# Learn

# [[menu.main]]
# name = "Learn"
# URL = "/workshops/"
# weight = 7

# Shop

[[menu.main]]
name = "Shop"
URL = "https://shop.susannahfisher.art/"
weight = 8

# About

[[menu.main]]
name = "About & Contact"
URL = "about/"
weight = 9

# footer menu

# [[menu.footer]]
# name = "Beautiful Ordinary Life Newsletter"
# URL = "https://beautifulordinarylife.substack.com/"
# weight = 10

[[menu.footer]]
name = "A Naturalist's Notebook Newsletter"
URL = "https://anaturalistsnotebook.substack.com/"
weight = 20

# [[menu.footer]]
# name = "workshops"
# URL = "workshops/"
# weight = 30

[[menu.footer]]
name = "Shop"
URL = "https://shop.susannahfisher.art/"
weight = 100


#################### default parameters ################################
[params]
logo = ""
home = "Home"
# Meta data
description = "Susannah Fisher is an illustrator and fine artist specializing in natural history illustration, nature journaling, visual journalism, and portrait painting."
author = "Susannah Fisher"
# Google Analitycs
googleAnalitycsID = "Your ID"
# Contact Information
mobile = ""
email = "info@susannahfisher.art"
location = ""
# copyright
copyright = "&copy; 2023 Susannah Fisher | All Rights Reserved <br> All artwork and images of artwork are the sole property of Susannah Fisher and may not be reproduced or sold for profit without written consent by the artist.<br>Web design & front-end development by the artist. Website built on the HUGO static site generator framework."

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# search
[params.search]
enable = true

############################ taxonomies ########################

[taxonomies]
  category = 'categories'
  tag = 'tags'

############################ news letter ########################
[params.newsletter]
enable = false
title = "Join Our Newsletter"
content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero"


# cookies
[params.cookies]
enable = true
expire_days = 2


############################# social site ########################

[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "https://instagram.com/susannahssketchbook"

[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "https://instagram.com/naturalists_notebook/"

[[params.social]]
title = "pinterest"
icon = "ti-pinterest" # themify icon : https://themify.me/themify-icons
link = "https://pinterest.com/smfisherart"

############################# html used in markdown ########################
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

