######################## default configuration ####################
baseURL = "https://susannahfisher.art/"
languageCode = "en-us"
title = "From The Easel"
theme = "liva-hugo"
summaryLength = "10"
paginate = 6
disqusShortname = ""

[outputs]
home = ["HTML", "RSS", "JSON"]

[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5

############################# Plugins ##############################
[params.plugins]

# CSS Plugins
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
URL = "plugins/venobox/venobox.css"

# JS Plugins
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
URL = "plugins/search/fuse.min.js"
[[params.plugins.js]]
URL = "plugins/search/mark.js"
[[params.plugins.js]]
URL = "plugins/search/search.js"


############################## navigation ###############################
[menu]

# main menu
# Projects

[[menu.main]]
identifier = "projects"
name = "Projects"
URL = "/projects"
weight = 1

[[menu.main]]
name = "Portraits"
parent = "projects"
URL = "projects/portraits/"
weight = 1

# [[menu.main]]
# name = "Nature Journals"
# parent = "projects"
# URL = "projects/nature-journals/"
# weight = 2

# [[menu.main]]
# name = "Illustration"
# parent = "projects"
# URL = "projects/illustration/"
# weight = 3

# [[menu.main]]
# name = "Book Arts"
# parent = "projects"
# URL = "projects/book-arts/"
# weight = 4

# [[menu.main]]
# name = "Mail Art"
# parent = "projects"
# URL = "projects/mail-art/"
# weight = 5

# Workshops

# [[menu.main]]
# identifier = "workshops"
# name = "Workshops"
# URL = "workshops/"
# weight = 2

# [[menu.main]]
# name = "Book Arts"
# parent = "workshops"
# URL = "workshops/book-arts/"
# weight = 1

# [[menu.main]]
# name = "Visual Journaling"
# parent = "workshops"
# URL = "workshops/journaling/"
# weight = 2

# Blog

[[menu.main]]
name = "Blog"
URL = "blog/"
weight = 30

# [[menu.main]]
# name = "Learning Communities"
# URL = "learning-communities/"
# weight = 35

# About

[[menu.main]]
name = "About"
URL = "about/"
weight = 50

# [[menu.main]]
# name = "Shop"
# URL = "https://shop.susannahfisher.art/"
# weight = 60

# footer menu

# [[menu.footer]]
# name = "Projects"
# URL = "projects/"
# weight = 20

# [[menu.footer]]
# name = "Workshops"
# URL = "workshops/"
# weight = 25

[[menu.footer]]
name = "Blog"
URL = "blog/"
weight = 30

# [[menu.footer]]
# name = "Learning Communities"
# URL = "learning-communities/"
# weight = 40

[[menu.footer]]
name = "About"
URL = "about/"
weight = 50

# [[menu.footer]]
# name = "Shop"
# URL = "https://shop.susannahfisher.art/"
# weight = 60


#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "Susannah Fisher is an artiist and illustrator specializing in Classical Realism art. From The Easel is a blog of inspiration, encouragement and behind-the-scenes glimpses from the artist's studio. Posts about projects, art tutorials, and thoughts about an artist's life."
author = "Susannah Fisher"
# Google Analitycs
googleAnalitycsID = "Your ID"
# Contact Information
mobile = ""
email = "info@susannahfisher.art"
location = ""
# copyright
copyright = "&copy; 2022 Susannah Fisher | All Rights Reserved <br> All artwork and images of artwork are the sole property of Susannah Fisher and may not be reproduced or sold for profit without written consent by the artist."

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# search
[params.search]
enable = true

############################ taxonomies ########################

[taxonomies]
  category = 'categories'
  genre = 'genres' # custom
  tag = 'tags'

############################ news letter ########################
[params.newsletter]
enable = false
title = "Join Our Newsletter"
content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero"


# cookies
[params.cookies]
enable = true
expire_days = 2


############################# social site ########################
[[params.social]]
title = "pinterest"
icon = "ti-pinterest" # themify icon : https://themify.me/themify-icons
link = "https://pinterest.com/smfisherart"

[[params.social]]
title = "youtube"
icon = "ti-youtube" # themify icon : https://themify.me/themify-icons
link = "https://www.youtube.com/channel/UCpIZrghBZk-VmV6OZ6HMcfw"

############################# html used in markdown ########################
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

